### ISSUE TITLE
'CTFReader' is not defined

### ISSUE THREAD

**Issue by electron2302** [wallento/pipeline-viewer#1]
I have this Error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/pipeline-viewer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pipelineviewer/main.py", line 218, in main
    render(pipelines[args.core](args.infile), args)
  File "/usr/local/lib/python3.6/dist-packages/pipelineviewer/ibex.py", line 13, in __init__
    self.ctf_reader = CTFReader(tracepath)
NameError: name 'CTFReader' is not defined
```

What is the missing component and how do i install it ?

**Comment by wallento** [comment]
Sorry, the README is still work-in-progress ;)
You need python-babeltrace for it to work. I think it is supposed to complain when its not installed, need to double check that part. Thanks for the report!

**Comment by electron2302** [comment]
Thanks for the very quick response, but `python3-babeltrace is already the newest version (1.5.5-1).`
So it must be something else

**Comment by wallento** [comment]
Ah, your babeltrace is outdated (1.5.5). I will look into it tonight, it is a minor patch to support it. I am thinking about replacing it with an entirely new Python CTF library in case you know someone interested in a thesis or job ;)
